columns_to_be_removed = [
    "abrasive cleaner",
    "artif. sweetener",
    "baby cosmetics",
    "bags",
    "baking powder",
    "bathroom cleaner",
    "bottled beer",
    "bottled water",
    "brandy",
    "cat food",
    "cleaner",
    "cling film/bags",
    "cookware",
    "curd",
    "decalcifier",
    "dental care",
    "detergent",
    "dish cleaner",
    "dishes",
    "dog food",
    "female sanitary products",
    "finished products",
    "flower (seeds)",
    "flower soil/fertilizer",
    "hair spray",
    "herbs",
    "house keeping products",
    "hygiene articles",
    "kitchen towels",
    "kitchen utensil",
    "light bulbs",
    "liqueur",
    "liquor",
    "liquor (appetizer)",
    "long life bakery product",
    "make up remover",
    "male cosmetics",
    "misc. beverages",
    "napkins",
    "newspapers",
    "oil",
    "pet care",
    "photo/film",
    "pip fruit",
    "pot plants",
    "preservation products",
    "prosecco",
    "pudding powder",
    "red/blush wine",
    "roll products ",
    "rubbing alcohol",
    "salty snack",
    "shopping bags",
    "skin care",
    "snack products",
    "soap",
    "soda",
    "softener",
    "soups",
    "sparkling wine",
    "specialty bar",
    "specialty cheese",
    "specialty chocolate",
    "specialty fat",
    "specialty vegetables",
    "toilet cleaner",
    "whisky",
    "white wine",
    "zwieback"
]